<?php
declare(strict_types=1);
/**
 * Lumora Gallery — Configuration
 *
 * This file is generated by the installer (/install/).
 * Copy to config.php and fill in your values if you are setting up manually.
 *
 * DO NOT expose this file publicly; it contains your database credentials.
 *
 * @copyright Copyright (C) 2025 Ariane
 * @license   GPL-3.0-or-later <https://www.gnu.org/licenses/gpl-3.0>
 */

// ── Database ──────────────────────────────────────────────────────────────────
define('DB_HOST',    'localhost');         // MySQL/MariaDB hostname
define('DB_NAME',    'your_database');    // Database name
define('DB_USER',    'your_user');        // Database username
define('DB_PASS',    'your_password');    // Database password
define('DB_PREFIX',  'lum_');             // Table prefix — change before install if sharing a DB
define('DB_CHARSET', 'utf8mb4');          // Leave as utf8mb4

// ── Installation flag ─────────────────────────────────────────────────────────
// Set to true only after the installer has completed successfully.
define('LUMORA_INSTALLED', true);
